### ISSUE TITLE
Instagram videos not displaying properly

### ISSUE THREAD

**Issue by in-a-midnight-song** [olleota/themes#149]
Issue: Instagram videos shared in Tumblr get truncated / only displays in half.

Theme Used: Fizz by Olle Ota

Sample permalinks:  

http://in-a-midnight-song.tumblr.com/post/84418536896/stoked-to-see-a-panda-in-real-life-for-the-first
http://in-a-midnight-song.tumblr.com/post/84414809331/the-red-panda-or-lesser-panda-is-said-to-be-the

**Comment by olleota** [comment]
@in-a-midnight-song I've pushed an update to all themes to fix this up, please update the theme at http://olleotathemes.tumblr.com/theme/fizz

Please reopen this issue if the problem persists :)
