### ISSUE TITLE
Adding a page

### ISSUE THREAD

**Issue by marissa1218** [olleota/themes#173]
I followed the steps on your guys website, and also off tumblr to create a tagged page, but whenever i click to go to it it says that the URL cannot be found. Im nearly positive i did it right but im still having this problem

**Comment by marissa1218** [comment]
whoaimaloser.tumblr.com 
Thanks!

**Comment by olleota** [comment]
I had a look at your links.

The issue seems to be you haven't include "http://", so you kitty link (and
other links) should be set to redirect to "
http://whoaimaloser.tumblr.com/tagged/kitty" instead.
