### ISSUE TITLE
Source doesn't show

### ISSUE THREAD

**Issue by Mystori06** [olleota/themes#174]
When posting new content, the source doesn't show up. Is this a problem with the Olle Ota Ash theme?

**Comment by Mystori06** [comment]
Thanks so much but we're not concerned about the "Via". Just the "source" as in who posted the photo. 

For example, when I post a photo (or most anyone else for that matter), my tumblr name shows up as the source of the post when someone reblogs the photo I posted. In the example you used below it would show: Source: demo

Here's an example of what I mean:



In this case, absolutminimum.tumblr.com is the person who originally posted the photo. And you can click on the source and it will take you to their tumblr page. But for Sunshine-cafe, nothing shows up when her photos are reblogged. Not even the word "source" like in almost every photo on tumblr. We think it must be related to the theme somehow. 

Any thoughts??

Thank you again, Olle!!

Tori

**Comment by olleota** [comment]
Hi Tori,

Could you upload a screenshot of the issue on Github at
https://github.com/olleota/themes/issues/174.

Could I also have a link to the affected post on a blog that uses an Olle
Ota Theme.

Thanks!

**Comment by Mystori06** [comment]
As requested, here's the link to one of sunshine-cafe's original posts that doesn't show her tumblr name as the source when it is reblogged. Sunshine-cafe uses the Olle Ota Ash theme:

http://sunshine-cafe.tumblr.com/post/106450016717

Here's the same post reblogged by yourbrown-eyes.tumblr.com from sunshine-cafe and it doesn't show sunshine-cafe as the source. 

http://yourbrown-eyes.tumblr.com/post/106570833137

I'm going to upload a screenshot of the issue to the GitHub link you provided now. 

Thanks again for all your help!

Tori

**Comment by Mystori06** [comment]
Well.....can't figure out how to upload screenshot from my iPhone to the GitHub link. My knowledge of these things is somewhat limited. 😁 Any tips?

THANK YOU!




Begin forwarded message:

> From: Rebecca <mystori06@aol.com>
> Date: December 31, 2014 at 22:55:50 CST
> To: olleota/themes <reply@reply.github.com>
> Subject: Re: [themes] Source doesn't show (#174)
> 
> As requested, here's the link to one of sunshine-cafe's original posts that doesn't show her tumblr name as the source when it is reblogged. Sunshine-cafe uses the Olle Ota Ash theme:
> 
> http://sunshine-cafe.tumblr.com/post/106450016717
> 
> Here's the same post reblogged by yourbrown-eyes.tumblr.com from sunshine-cafe and it doesn't show sunshine-cafe as the source. 
> 
> http://yourbrown-eyes.tumblr.com/post/106570833137
> 
> I'm going to upload a screenshot of the issue to the GitHub link you provided now. 
> 
> Thanks again for all your help!
> 
> Tori
>

**Comment by olleota** [comment]
Hi Tori,

I believe you have to log into Github using Mystori06 as your username on a
desktop computer (Windows, Mac, Linux should all work).

From there you just drag and drop an image into the Github comment box.

The link you provided me is not an Olle Ota Theme, both the blogs are using
themes by different theme developers. For reference Ash looks like the
screenshot at http://olleotathemes.tumblr.com/theme/ash.

Thanks,

Olle

**Comment by Mystori06** [comment]
Hi Olle,

I just talked to my friend and found out she did indeed change her theme a few days ago because of the "source" problem.

I don't know what else to do at this point. I thought this would be an easy fix. 

She loves the Ash theme and wants to change it back if the problem can be rectified. 

Tori

**Comment by olleota** [comment]
Hi Tori,

Could you confirm that this issue is fixed when they use a different theme?

Thanks,

Olle
