### ISSUE TITLE
Retrospective- Avatar picture

### ISSUE THREAD

**Issue by emmamaria** [olleota/themes#175]
From the theme preview, I was under the impression that the shown circle with glasses was where a avatar picture went, however I'm not sure if there isnt one or it just isnt showing. Could you please clarify whats gone wrong, or how I can add one (if you're comfortable with telling me). Thank you :)

**Comment by olleota** [comment]
Hi @emmamaria 

Yep, the theme supports avatars.

Open up the customize panel and select "Masthead avatar" to enable your avatar.

![avatar](https://cloud.githubusercontent.com/assets/6053890/5603962/5d3374e8-93f2-11e4-883c-1558a83f3876.png)
