### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by BeforeTheStorm** [olleota/themes#176]
Hey, I am not sure if it is just me but I am having big problems with the theme someday. I have edited it slightly but only using the settings provided (If that makes sense). I am happy with the way it looks but when I went to my blogs web address I noticed that it was as normal but then when I scroll down, It is all duplicated? Hope thats all clear! If not, you can look at my blog http://lousarchive.tumblr.com

Thanks!
Lou

**Comment by olleota** [comment]
Hi Lou,

Could you try installing the theme again, it looks like it was pasted twice.

Thanks
