### ISSUE TITLE
Unable to see "Read More"s.

### ISSUE THREAD

**Issue by Kazul9** [olleota/themes#179]
kkazulwolf.tumblr.com
Firefox 35
I've normally been able to see the "Read More" cuts at the bottom of a given post, but for some reason on your Franz theme, it doesn't show up. I've also looked on another computer on the latest version of Chrome, and there's nothing there. I really love this theme and want to keep using it, but my site relies on those "Read More"s. Help?

**Comment by olleota** [comment]
Unable to reproduce the issue.

Please link to an affect page of the blog.

Thank you!
