### ISSUE TITLE
GRID Theme Page Break

### ISSUE THREAD

**Issue by nathandowney** [olleota/themes#182]
I've been using the Olleota "GRID" theme and have been experiencing some issues with the page break, leading to a white gap between images (see screenshot). Strangely, it occurs irregularly and in different locations down the page every time. I have my "posts per page" set to 10 in the screenshot below.
![screen shot 2015-01-28 at 10 11 13 am](https://cloud.githubusercontent.com/assets/10744728/5942669/3dbc6362-a6d6-11e4-91bd-30487df8ac40.png)

URL:  paradiseprowling.tumblr.com
Browser: Chrome (Version 40)

**Comment by olleota** [comment]
@nathandowney Could you please update to the latest version of Grid and see if the issue persists.
