### ISSUE TITLE
Can enlarge only images in posts with more than 2 pictures

### ISSUE THREAD

**Issue by sluganda** [olleota/themes#184]
Hello,

sorry about long and weird name of the topic, but that's pretty much it. 
My blog is running amazing RUBIC theme. I've got issue when on index page, can enlarge images in single picture posts. When there's more than one picture, everything runs fine and little magnifying glass show up etc.

Any thoughts? Thank you in advance. 

My blog:
http://fanriot.tumblr.com/

**Comment by olleota** [comment]
@sluganda Currently the "zoom" photoset only has limited availability.
