### ISSUE TITLE
I fixed clickable of media play(soundcloud, vimeo, youtube...) but I don`t want to see post date.

### ISSUE THREAD

**Issue by rulrulra** [olleota/themes#185]
Hello
My theme is GALLERY.
as your method, off the post buttons
So I fixed clickable of media play(soundcloud, vimeo, youtube...)

But I don`t want to see post date...
and not working ☟↓⇓⇩⇣
<<<<http://olleotathemes.tumblr.com/support/css
Hide post date (grid themes only)
To hide the post date that shows up when you click on a post permalink use:
.permalink .post-hover { display: none; }>>>>

 Just, I want to turn on the POST BUTTONS and clickable media play(soundcloud, vimeo, youtube...)

Could you help me?

**Comment by olleota** [comment]
At the moment you have to click through the permalink, unless you disable the "post button" feature.

See #72 and #20 for more discussion
