### ISSUE TITLE
Soundcloud Player not showing up

### ISSUE THREAD

**Issue by foreignfaction** [olleota/themes#186]
hey my tumblr is foreignfaction.tumblr.com and i have your theme los angeles. My browser is Chrome 39.

I've put the link for my soundcloud playlist in the part where it says Soundcloud Link For Player and i clicked update preview, save, etc. And the player isn't showing up. The playlist is public and all too.

**Comment by olleota** [comment]
@foreignfaction There is an issue SoundCloud player we are using, so I have removed the SoundCloud feature in the latest update
