### ISSUE TITLE
Logo remove

### ISSUE THREAD

**Issue by jeremikurz** [olleota/themes#187]
Hello Olleota:)

Link for logo remove :

http://olleotathemes.tumblr.com/post/105259303290/new-option-to-remove-olle-ota-theme-logo

Does not exist. Maybe it was replaced? Thanks for your ultimate themes - i'd like to donate you - any chance?

Thanks J.

**Comment by olleota** [comment]
@jeremikurz To remove the logo:

1. Update to the latest version of your theme
2. Unselect the "Link to Olle Ota Themes" toggle

![link](https://cloud.githubusercontent.com/assets/6053890/6205586/96c2071e-b5c7-11e4-9a35-562cf24a8d09.png)

Thanks for using our themes, though we don't accept donations.

**Comment by olleota** [comment]
We no longer include a logo in the theme. We've changed over to a link that points to the theme instead.
