### ISSUE TITLE
Multiple Edit Theme/Dashboard Buttons

### ISSUE THREAD

**Issue by alexiana5407** [olleota/themes#189]
Hey I have been recently experiencing a bug in which I have two Edit Theme/Dashboard buttons on my blog... There is a screenshot down below. 
![screen shot 2015-02-17 at 2 51 11 am](https://cloud.githubusercontent.com/assets/11043442/6227400/08312d62-b654-11e4-9246-6c261ce60dd3.png)

URL: http://glitterpussyyy.tumblr.com/
Browser: Mozilla Firefox

**Comment by olleota** [comment]
Hi @alexiana5407

I believe the issue is caused by having a 3rd party music player, could you
try removing it and see if the issue persists?
