### ISSUE TITLE
Date not showing up?

### ISSUE THREAD

**Issue by natw888** [olleota/themes#190]
Hiya

I am using the Theme POLYMER, and I am new to tumblr in general..

I was wondering how you put your Dates underneath the post like the sample picture you provided for this theme? - Currently I can not see this on my tumblr page and it's frustrating for me.

http://nobodee-rs.tumblr.com/ is my tumblr (It does not show date below the picture)

**Comment by olleota** [comment]
@natw888 Looks like you have got dates showing up already
