### ISSUE TITLE
None of the themes are working for me

### ISSUE THREAD

**Issue by kakakak** [olleota/themes#191]
For some strange reason none of the themes are working for me on tumblr. I've copied the theme entirely then pasted in the custom css section under the advanced settings heading on my customization page. Please help me fix!!

**Comment by olleota** [comment]
Hi @kakakak

To install a theme please follow the instructions at
http://olleotathemes.tumblr.com/support/install

The code should not be pasted in the "custom css" section, rather it should
be put in the "Edit HTML" panel.

Please see the above link for more info.
