### ISSUE TITLE
All one-column themes fuck the code forever

### ISSUE THREAD

**Issue by eatmoarfish** [olleota/themes#192]
Hi, I'm at eatmoarfish.tumblr.com

I tried pasting your code into my blog, and now, it's ruined my whole blog. No matter if I go back to chose a normal Tumblr free theme, it gives me this ridiculous embedded code. What have you people done to my blog?!

![screen shot 2015-02-22 at 11 02 17 pm](https://cloud.githubusercontent.com/assets/11155070/6323436/453ce128-bae7-11e4-8b57-5e8ac6464094.png)

-EMF

**Comment by olleota** [comment]
Hi EMF,

Sorry to hear you were unable to install our themes.

To revert to the default Tumblr theme, first visit
http://www.tumblr.com/theme/37310 then click "Install" and select your blog
you wish to revert.

Regards,

Olle
