### ISSUE TITLE
Google Fonts Not Working

### ISSUE THREAD

**Issue by 4er0d0wn** [olleota/themes#194]
(Early preface: I haven't modified any of the HTML)

When I go to use a Google Font, none work and it simply reverts to a default font style. Source Sans / Source Sans Pro - Are the only two fonts that work.

I tried manually fixing it, but to no avail (tried Googling for a solution, but couldn't find anything in the code they were describing, then tried to figure it out myself with no luck.) So I reverted the changes (exit without saving), and am back to default HTML, aside from the changes available in the user-interface.

http://thecoffeelovestory.tumblr.com/
Chrome / Version 40.0.2214.115 m

**Comment by olleota** [comment]
Please provide an example of an affected blog running an Olle Ota Theme.
