### ISSUE TITLE
Organizing HTML code

### ISSUE THREAD

**Issue by KGrantSuttie** [olleota/themes#195]
Hello-

I'm using your Rhythm theme on my tumblr site: http://battlegroundproductions.tumblr.com.
Though two web designers and myself have made some inroads manually, the raw HTML & CSS in the customization section looks very messy, making it hard to read, organize & customize. When we used an external code clean up, it jumbles the appearance.
This doesn't seem strictly customization related. Is there a way to keep this theme's code better organized to facilitate customization? I love the foundational theme but I don't want to waste mine or additional designers' time sifting through to make simple & small changes
![screenshot 1](https://cloud.githubusercontent.com/assets/11301265/6471668/de494c9c-c1a1-11e4-805c-99d11b6966d1.png)

**Comment by olleota** [comment]
@KGrantSuttie Right now there is not a better organized HTML one available. We are working on it.
