### ISSUE TITLE
Pocket Folio theme, posts not appearing side by side but one above the other?

### ISSUE THREAD

**Issue by jsalowe** [olleota/themes#196]
My URL is http://jsalowe.tumblr.com or http://jsalowe.co.vu and I've tried everything I could think of, including changing the number of posts per page, changing back and forth from infinite scroll, even finally adding your suggested custom CSS to get a different post width, etc.—but no matter what I do, my posts appear in a long narrow row up and down on the page instead of side by side as in your screenshot. Any help would be appreciated—thank you so much! I love the elegance & flexibility of the theme, otherwise. (Oh, and I run the latest version of Chrome on a Mac but the problem can be reproduced in Ffox/Safari).

**Comment by olleota** [comment]
@jsalowe Remove the custom CSS rule for:
.three-col.index article {
    width: 95%;
}

**Comment by jsalowe** [comment]
Thanks but as l said it was doing that before l added the custom css, l actually added that to try to fix it. lt's cool, l just gave up on having more than one post, and made it page-width. Thanks again!

**Comment by olleota** [comment]
If you reinstall from scratch I can have a look at it from here

**Comment by olleota** [comment]
You have quite an old version of the theme.

You can grab the new on at http://olleotathemes.tumblr.com/theme/pocket-folio
