### ISSUE TITLE
Really quick question regarding Franz Theme

### ISSUE THREAD

**Issue by styrofoamnoise** [olleota/themes#197]
Hi, I know you aren't offering custom CSS so I'm not asking for a complete theme makeover. I'm using the Franz theme and I want to make the banner smaller (in height) but I can't find which variable I have to change. Could you please point me in the right direction? I went over the html several times and even isolated the specific html code that calls the CSS for the banner but even when I trace it I can't seem to find the variable. All I need to know is the class ID that it is using and I can figure out the rest myself.

Thanks :)

**Comment by olleota** [comment]
To find the class of something: right click on it in Chrome or Firefox and select "Inspect Element"
