### ISSUE TITLE
Heading font for text posts and asks have glitches

### ISSUE THREAD

**Issue by aansaa** [olleota/themes#198]
I'm using the retrospective theme and the headings for text posts are huge. Also, they don't fit in with the "Arquitecta" font I use. Plus, the anonymous questions have huge headings while my answers are normal. Also, anons are not in their default theme (the box around the questions). 
Please help me fix this problem, I've tried everything I could to fix it.
Thank you

elysiangazes.tumblr.com

**Comment by olleota** [comment]
@imonuba Right now we do not offer custom design changes
