### ISSUE TITLE
POLYMER header missing?+ Permalink content  not really visible

### ISSUE THREAD

**Issue by imonuba** [olleota/themes#200]
Dear olleota.

Your themes are absolutly best form every themes i ever found on net.
I love it!! and so love you work.

I got problem on POLYMER theme.
I cannot find header so i must put all my main info into description box. ok. but when i go to permalink of post ----- permalink item itself is so deep under the discription  that its like off the page....

Result will be the same with info filled in header.....so that wont help anyway  i think.  But what would help a lot is to HIDE descirption when in permalink page....so permalink content is right after the logo. IS IT POSSIBLE? 

I like verymuch how this is solved in SHADE THEME where whole masthead is on left side and content is right next to it. But that i think is not possible to make in POLYMER ? 

p.s.: maybe  the solution is to just move permalink post to the right from the masthead? is it possible ?

Can you help please?
THANKS FOR YOUR THEMES!!! best.  regards imon

**Comment by olleota** [comment]
@imonuba Right now we do not offer custom design changes

**Comment by imonuba** [comment]
Ok. Thanks for answer very much.  your themes are the BEST no doubt.
