### ISSUE TITLE
Square images being stretched vertically in Geometric theme.

### ISSUE THREAD

**Issue by nursethalia** [olleota/themes#201]
Hello,

Today I suddenly began experiencing a few images being stretched on my my blog, which uses the Geometric theme. I've tried editing the posts and reuploading the images, but it doesn't help with the issue.

My tumblr blog address is http://www.miyadraws.com. As you can see, three of the images near the top are badly stretched (the original images are all square). This is the first time this has happened while using this theme, and I can't for the life of me figure out what happened; those same three images appeared fine yesterday. I have tried viewing my blog in Safari, Firefox, and Chrome, and those three images are all affected in each browser. I made one new post, and the image posted just fine, in the right aspect ratio.

**Comment by imonuba** [comment]
Madam , this is what i see  and it looks normal.  ( link down )
Or iam missing something?
One day i had similar problem---my theme just crashed and only think halped, was rebuild blog form a scratch. Its like, impossible to happen....i was very confused. hope its not your issue anymore- simon.


http://s14.postimg.org/ld8qiqj81/Screen_shot_2015_03_17_at_10_45_02_AM.png

**Comment by nursethalia** [comment]
Huh, that's really odd. It's still showing incorrectly for me on my computer and tablet. I took a screenshot: http://i31.photobucket.com/albums/c390/nursethalia/issuesgeometric.jpg

But if it's showing up to other people correctly, I guess that's good - that was my main concern. Thanks for checking, Simon. I've tried reinstalling the theme and it didn't help. I'll just have to deal with it and remind myself that others aren't seeing it as messed up as I am!

**Comment by imonuba** [comment]
i forgot to mantion, that iam on MAC OSX (10.6)  . there might be also diferences between windows and mac osx and in versions also.

But i dont know much about it.  

Regards

**Comment by nursethalia** [comment]
I'm using a Mac too, same version of OS.

**Comment by imonuba** [comment]
haah )))))...   yea''  avoiding problems'')))))

**Comment by nursethalia** [comment]
FIXED IT!

Okay, this was only happening on posts where I was answering an ask, so I opened up the post for editing and, clicking the little gear symbol, changed the text editor from rich text to html. Then, every time it mentioned image width and height, I changed it from 1000 pixels to "auto". Saved, reloaded page... stretching fixed for that image!!!

**Comment by olleota** [comment]
@nursethalia Good to hear. You need to remove fixed width and height from images or they play up in Tumblr.
