### ISSUE TITLE
Dates not showing on Concrete theme.

### ISSUE THREAD

**Issue by ashniderman** [olleota/themes#203]
http://shniderman.tumblr.com/ 

Thanks.

Adi

**Comment by olleota** [comment]
@ashniderman Please set the option via the customize panel.

**Comment by ashniderman** [comment]
Hi, 
Thanks for your reply. This theme is  incredible, something i was looking for, for a long time.
If you can tell me which of the setting it is, ill greatly appreciate it. I can seem to find anything that suggest dates.
Thanks.

Adi

**Comment by olleota** [comment]
@ashniderman Turn off the post buttons.

Thanks,

Olle

**Comment by ashniderman** [comment]
Thanks again!

Adi
